// SmartThings
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES'
export const REQUEST_DEVICES = 'REQUEST_DEVICES'

// Sonos
export const RECEIVE_PLAYER = 'RECEIVE_PLAYER'
export const REQUEST_PLAYER = 'REQUEST_PLAYER'
export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE'
