// SmartThings
export const REQUEST_DEVICES = 'REQUEST_DEVICES'
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES'

// Sonos
export const REQUEST_PLAYER = 'REQUEST_PLAYER'
export const RECEIVE_PLAYER = 'RECEIVE_PLAYER'
export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE'

// Weather
export const REQUEST_WEATHER = 'REQUEST_WEATHER'
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER'
